#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#include <stdint.h>

/* Keys are connected to ground when pressed. */
#define BOARD_KEY_DEFAULT_ACTIVE_LOW 1u
#define BOARD_KEY_DEFAULT_DEBOUNCE_MS 8u
#define BOARD_KEY_DEFAULT_LONG_PRESS_MS 1000u

/* The original board uses an active-high buzzer. */
#define BOARD_BUZZER_DEFAULT_ACTIVE_LOW 0u

/* Line sensor indices run from the vehicle's left side to its right side. */
#define BOARD_LINE_SENSOR_DEFAULT_ACTIVE_LOW 0u
#define BOARD_LINE_SENSOR_INDEX0_IS_LEFT 1u

#define BOARD_TB6612_PWM_MAX_DUTY 1000u
#define BOARD_TB6612_PWM_PERIOD_COUNTS 4000u
#define BOARD_TB6612_LEFT_MOTOR_INVERTED 1u
#define BOARD_TB6612_RIGHT_MOTOR_INVERTED 0u

#define BOARD_TB6612_LEFT_IN1_PORT TB6612_DIR_PORT
#define BOARD_TB6612_LEFT_IN1_PIN TB6612_DIR_AIN1_PIN
#define BOARD_TB6612_LEFT_IN2_PORT TB6612_DIR_PORT
#define BOARD_TB6612_LEFT_IN2_PIN TB6612_DIR_AIN2_PIN
#define BOARD_TB6612_RIGHT_IN1_PORT TB6612_DIR_PORT
#define BOARD_TB6612_RIGHT_IN1_PIN TB6612_DIR_BIN1_PIN
#define BOARD_TB6612_RIGHT_IN2_PORT TB6612_DIR_PORT
#define BOARD_TB6612_RIGHT_IN2_PIN TB6612_DIR_BIN2_PIN

/*
 * Quadrature counts per gearbox output revolution (x4 edge decoding).
 * Recalibrate this value if one physical wheel revolution does not report
 * 1500 counts on the new encoder wiring (measured at the wheel output).
 */
#define BOARD_ENCODER_OUTPUT_PULSES_PER_REV 1500u
#define BOARD_ENCODER_LEFT_INVERTED 0u
#define BOARD_ENCODER_RIGHT_INVERTED 1u

#define BOARD_WHEEL_DIAMETER_MM 65u
#define BOARD_WHEEL_CIRCUMFERENCE_UM \
    ((BOARD_WHEEL_DIAMETER_MM * 31416u) / 10u)

/* Speed targets use encoder counts per control period. */
#define BOARD_CONTROL_TASK_PERIOD_MS 10u
#define BOARD_CHASSIS_RATED_SPEED_RPM 300u
#define BOARD_DIRECT_300_RPM_TEST 0u
#define BOARD_CHASSIS_RATED_SPEED_DELTA                                     \
    ((BOARD_ENCODER_OUTPUT_PULSES_PER_REV * BOARD_CHASSIS_RATED_SPEED_RPM * \
      BOARD_CONTROL_TASK_PERIOD_MS) /                                       \
     60000u)
#define BOARD_CHASSIS_DEFAULT_SPEED_RPM 100u
#define BOARD_CHASSIS_DEFAULT_SPEED_DELTA                                     \
    ((BOARD_ENCODER_OUTPUT_PULSES_PER_REV * BOARD_CHASSIS_DEFAULT_SPEED_RPM * \
      BOARD_CONTROL_TASK_PERIOD_MS) /                                         \
     60000u)

#define BOARD_CHASSIS_LEFT_SPEED_PID_KP 30
#define BOARD_CHASSIS_LEFT_SPEED_PID_KI 5
#define BOARD_CHASSIS_LEFT_SPEED_PID_KD 0
#define BOARD_CHASSIS_RIGHT_SPEED_PID_KP 30
#define BOARD_CHASSIS_RIGHT_SPEED_PID_KI 7
#define BOARD_CHASSIS_RIGHT_SPEED_PID_KD 0
#define BOARD_CHASSIS_SPEED_PID_SCALE 100
#define BOARD_CHASSIS_SPEED_PID_INTEGRAL_MIN (-1200)
#define BOARD_CHASSIS_SPEED_PID_INTEGRAL_MAX 1200
#define BOARD_CHASSIS_SPEED_PID_OUTPUT_MIN (-1000)
#define BOARD_CHASSIS_SPEED_PID_OUTPUT_MAX 1000
/* Independent PWM feedforward, range 0..1000. */
#define BOARD_CHASSIS_LEFT_SPEED_FEEDFORWARD_AT_RATED 888
#define BOARD_CHASSIS_RIGHT_SPEED_FEEDFORWARD_AT_RATED 910

#endif
